### ISSUE TITLE
Use the SPDX formatted license

### ISSUE THREAD

**Issue by major** [redhatcloudx/observability-aws-cloudwatch#4]
The `License:` line in the spec file should use one of the updated [SPDX abbreviations](https://spdx.org/licenses/).

**Comment by F-X64** [comment]
@major The base package will use "Apache-2.0" we need to use the same license, right?

**Comment by major** [comment]
@FKolwa That should be fine! 👍

**Comment by miyunari** [comment]
I added the `apache-2.0` licence in this PR https://github.com/redhatcloudx/observability-aws-cloudwatch/pull/6/files
