### ISSUE TITLE
Missing requirements for the base OTEL package

### ISSUE THREAD

**Issue by major** [redhatcloudx/observability-aws-cloudwatch#5]
_I assume there's a plan to add this later, but I figured it was worth opening an issue so you don't forget!_

Be sure to add a `Requires:` for the base OTEL package to this spec so that anyone installing the configuration will get the OTEL bits as well.

**Comment by miyunari** [comment]
I added `requires:` in this PR https://github.com/redhatcloudx/observability-aws-cloudwatch/pull/6
